# SPDX-License-Identifier: FSFAP

################################################################################
#
# Copyright (c) 2022 Jeffrey H. Johnson <trnsz@pobox.com>
#
# Copying and distribution of this file, with or without modification,
# are permitted in any medium without royalty provided the copyright
# notice and this notice are preserved.  This file is offered "AS-IS",
# without any warranty.
#
################################################################################

[profile.release]
opt-level = 3
debug = 0
overflow-checks = false
debug-assertions = false
lto = 'fat'
panic = 'abort'
incremental = false
codegen-units = 1
rpath = false

[profile.release.build-override]
opt-level = 3
codegen-units = 1

[profile.dev.package."*"]
opt-level = 3
codegen-units = 1
