[profile.release]
opt-level = 3
debug = 0
overflow-checks = false
debug-assertions = false
lto = 'fat'
panic = 'abort'
incremental = false
codegen-units = 1
rpath = false

[profile.release.build-override]
opt-level = 3
codegen-units = 1

[profile.dev.package."*"]
opt-level = 3
codegen-units = 1

[target.x86_64-unknown-linux-musl]
rustflags = ["-C", "target-feature=+crt-static"]
